version: '3.6'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./servers:/etc/nginx/conf.d
      - ./html:/Users/whitearctic/dev/nginx