version: "3.7"

services:
  db:
    image: postgres
    volumes:
      - PGDATA:/var/lib/postgresql/data
    environment:
        POSTGRES_DB: screenmatch-phrases
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    ports:
        - "5433:5432"
    networks:
        - screenmatch-phrases-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: screenmatch@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "15432:80"
    depends_on:
      - db
    networks:
        - screenmatch-phrases-network

networks:
  screenmatch-phrases-network:
    driver: bridge

volumes:
    PGDATA:
